project:
  type: website
  render:
    - "*.qmd"
    - "*.html"
    - "!README.md"
    - "!LICENSE.md"
  preview:
    port: 4321
    browser: true    
execute:
  # Re-render only when source changes
  freeze: auto
description-meta: "Jenny Wong's personal website."

website:
  title: "jnywong.github.io"
  site-url: "https://jnywong.github.io"
  repo-url: https://github.com/jnywong/jnywong.github.io
  description: "Jenny Wong's personal website."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: presentations.qmd
        text: Presentations
      - href: projects.qmd
        text: Projects        
      - href: "https://jnywong.github.io/2022-10-31-birmingham/"
        text: Software Carpentries
  page-footer:
    left: |
      {{< fa regular copyright >}} Jenny Wong, 2023<br>
      Opinions my own
    center: |
      [<img id="badge-license" src="http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png">](http://creativecommons.org/licenses/by-nc-sa/4.0/ alt="CC-BY-NC-SA")<br>
      Licensed under CC BY NC SA
    right: |
      Made with [Quarto](https://quarto.org/) <br>
      Source on [GitHub](https://github.com/jnywong/jnywong.github.io/)

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false



