---
title: "About"
---

I am a Senior Research Software Engineer and joined the [Advanced Research Computing](https://intranet.birmingham.ac.uk/it/teams/infrastructure/research/index.aspx) department at the University of Birmingham, UK, in December 2021. I have a strong technical background, with over 8 years engaged in STEM research across the UK and France. My strength is in mathematics and numerical modelling, with experience using HPC to run cutting-edge simulations.

I am currently responsible for developing and operationalising a space weather forecasting model, which ingests up to 250GB of data per hour of live data streams from global navigation satellite systems and radar. My expertise in high-performance computing and data engineering enables the seamless integration of high-quality observational data with data assimilation modelling to produce high-fidelity forecasts of space weather in the Earth's ionosphere. I orchestrate this computationally intensive process by writing custom asynchronous task queues to distribute processes across computer clusters and combine the resulting outputs into a user-friendly web framework for analysis and visualisation, achieved using Celery, Django and Plotly. I also achieved 5x the performance of the data assimilation through code profiling and parallelising routines. This product is developed in collaboration with ESA and the UK Met Office.

I am also responsible for providing the research software support service of the EPSRC Tier 2 [Baskerville](https://www.baskerville.ac.uk/) supercomputer, a national facility in which I manage stakeholder relationships with The Alan Turing Institute, The Rosalind Franklin Institute, and Diamond Light Source (the UK’s national synchrotron). I regularly engage and support researchers with writing documentation, creating video tutorials, and designing and delivering training events to enhance accessibility to compute. For example, I have designed and delivered several data engineering and deep learning Jupyter notebook courses as a qualified [NVIDIA DLI](https://www.nvidia.com/en-gb/training/) and [Software Carpentries](https://carpentries.org/) Instructor, and I maintain the [Baskerville HPC GitHub](https://github.com/baskerville-hpc) repo.

## Experience

**University of Birmingham, Birmingham** \
*Senior Research Software Engineer* \
December 2021 - Present

- Accelerating and profiling data assimilation codes
for space weather forecasts, which ingest up to
250GB per hour of data from hundreds of stations
globally, and implementing interactive, web-based
visualisations.
- Certified NVIDIA Instructor providing data
engineering and deep learning training for
researchers, and general high-performance
computing support.

**Institut des Sciences de la Terre, Grenoble** \
*Postdoctoral Researcher* \
July 2020 - November 2021

- Developed a model of differential equations
describing the physics of phase change and
compaction of a solid-liquid system, and solved
them using finite volume methods in Python.

**Institut de Physique du Globe de Paris, Paris** \
*Postdoctoral Researcher* \
February 2019 - July 2020

- Ran large-scale numerical simulations solving the
magneto-hydrodynamic equations describing the
Earth’s dynamo on high-performance computers
using Fortran and OpenMP, and post-processed
large data sets in Python.

## Education

**University of Leeds, Leeds** \
*PhD, MSc Fluid Dynamics* \
September 2014 - February 2019 \
[Thesis](https://etheses.whiterose.ac.uk/23167/): A Slurry Model of the F-Layer in the Earth’s Core

**University of Leeds, Leeds** \
*MMath, BSc Mathematics* \
September 2009 - July 2013 \
First Class Honours

{{< downloadthis media/jenny-wong-2023.pdf dname="jenny-wong-2023" label="Download CV (PDF)" >}}

## Publications

**[A regime diagram for the slurry F-layer at the base of Earth's outer core](https://www.sciencedirect.com/science/article/am/pii/S0012821X21000509)** \
*J Wong, CJ Davies, CA Jones* \
Earth and Planetary Science Letters 560, 116791 (2021)

**[Stably stratified layers within Earth's core](https://www.research-collection.ethz.ch/bitstream/handle/20.500.11850/520577/1/Hardy_2019.pdf)** \
C Hardy, J Wong \
Astronomy & Geophysics 60 (3), 3.30-3.35 (2019) \

**[A Boussinesq slurry model of the F-layer at the base of Earth’s outer core](https://academic.oup.com/gji/article-pdf/214/3/2236/36134435/ggy245.pdf)** \
*J Wong, CJ Davies, CA Jones* \
Geophysical Journal International 214 (3), 2236-2249 (2018)

**[Design and operation of a Rayleigh Ohnesorge jetting extensional rheometer (ROJER) to study extensional properties of low viscosity polymer solutions](https://eprints.whiterose.ac.uk/113583/1/revised_version.pdf)** \
*E Greiciunas, J Wong, I Gorbatenko, J Hall, MCT Wilson, N Kapur, et al.* \
Journal of Rheology 61 (3), 467-476 (2017)